[package]
name = "objective"
version = "0.1.0"
edition = "2021"
authors = ["Drumstickz64"]
description = "A basic importer for the Wavefront .obj file format"

[dev-dependencies]
macroquad = "0.4.13"
